apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-booking-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Nishit556/ticket-booking-assignment.git
    targetRevision: HEAD
    path: k8s-gitops/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
