apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: event-catalog
  template:
    metadata:
      labels:
        app: event-catalog
    spec:
      containers:
      - name: event-catalog
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/ticket-booking/event-catalog:latest
        ports:
        - containerPort: 5000
        env:
        # We will get this Hostname from Terraform Outputs later
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: host
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password 
---
apiVersion: v1
kind: Service
metadata:
  name: event-catalog
  labels:
    app: event-catalog
spec:
  selector:
    app: event-catalog
  ports:
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
