apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 45.7.1
    helm:
      parameters:
      - name: grafana.service.type
        value: LoadBalancer # Exposes Grafana Dashboard via a Public URL
      - name: prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues
        value: "false"
      - name: prometheus.prometheusSpec.podMonitorSelectorNilUsesHelmValues
        value: "false"
      - name: prometheus.prometheusSpec.ruleSelectorNilUsesHelmValues
        value: "false"
      values: |
        prometheus:
          enabled: true
          prometheusSpec:
            serviceMonitorSelector:
              matchLabels:
                release: monitoring-stack
            serviceMonitorNamespaceSelector:
              matchNames:
              - default
              - monitoring
            podMonitorSelector:
              matchLabels:
                release: monitoring-stack
            podMonitorNamespaceSelector:
              matchNames:
              - default
              - monitoring
        grafana:
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
              - name: Prometheus
                type: prometheus
                uid: prometheus
                access: proxy
                isDefault: true
                url: http://monitoring-stack-kube-prom-prometheus.monitoring:9090
                editable: false
                jsonData:
                  httpMethod: GET
              - name: Loki
                type: loki
                uid: loki
                access: proxy
                url: http://loki-stack:3100
                editable: false
                jsonData:
                  maxLines: 1000
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true